export const projects = [
  {
    title: 'eHouse MarketPlace',
    description: "This is a very unique and simple Online MarketPlace where Owners of Properties (Landlords), can List their House Either for sale or for renting purpose, and anyone from around the world can explore houses within their Location, and choose a House that suit their Interest, Based on the Owners Listings Propersties.",
    image: 'https://firebasestorage.googleapis.com/v0/b/house-marketplace-b3077.appspot.com/o/portfolio%2Fhousemarket.png?alt=media&token=2fb411f2-51f7-49d4-8ab9-a2acc4139f91',
    tags: ['React', 'FireBaseDB'],
    source: 'https://house-marketplace-dabdu.vercel.app/',
    visit: 'https://vercel.com/dabdu/house-marketplace',
    id: 0,
  },
  {
    title: 'Cookies Ecommerce & Delivery App',
    description: "An app that allows users to buy any cookies, snacks, or drinks of their choose and also have delivery platform where riders and admin manages orders and users keep track of their purchase till arrival period.",
    image: 'https://firebasestorage.googleapis.com/v0/b/house-marketplace-b3077.appspot.com/o/portfolio%2Fcookies.png?alt=media&token=829d6d4d-1a01-4999-8778-98d704b568a0',
    tags: ['React', 'Redux', 'FireBaseDB'],
    source: 'https://house-marketplace-dabdu.vercel.app/',
    visit: 'https://vercel.com/dabdu/house-marketplace',
    id: 1,
  },
  {
    title: 'Tech Blog App',
    description: "Blog App built with NextJS with GraphQL (API Query Languages), GraphCMS gives US instant GraphQL Content APIs that allows to create, manages and deliver our content across platforms.",
    image: 'https://firebasestorage.googleapis.com/v0/b/house-marketplace-b3077.appspot.com/o/portfolio%2Ftechblog.png?alt=media&token=20afb370-8412-46b2-a15b-a1d51c25a7f1',
    tags: ['NextJS', 'Graphql', 'GraphCMS', 'Tailwind CSS'],
    source: 'https://github.com/dabdu/techblog-NextGraphql',
    visit: 'https://techblog-nextjs-graphql.vercel.app/',
    id: 1,
  },
  {
    title: 'GitHub Profile Finder',
    description: "This is a React JS App, that allows your to search for Github user's Profiles and see their profile details Such as user's Projects, Respositories, Followers&Following, Contributions, Commits, Stars etc.",
    image: 'https://firebasestorage.googleapis.com/v0/b/house-marketplace-b3077.appspot.com/o/portfolio%2F2.PNG?alt=media&token=1c25577f-8571-4e7a-89e2-a5d8003a2afe',
    tags: ['React', 'Tailwind CSS', 'GitHub-Api'],
    source: 'https://github.com/dabdu/github-user-finder',
    visit: 'https://github-user-finder-gamma.vercel.app/',
    id: 2,
  },
  {
    title: 'FeedBack App',
    description: "This is a Feedback App built on MERN Technologies, Backend Deploy on Heroku and Frontend on Vercel, Its allows customers to give the feedback on a particular product Sold or service rendered by the Company, so they can serve their Clients Much more Better.",
    image: 'https://firebasestorage.googleapis.com/v0/b/house-marketplace-b3077.appspot.com/o/portfolio%2F3.PNG?alt=media&token=1c8139bb-7a72-4a3d-a8b8-e97f2c407f39',
    tags: ['MongodB', 'ExpressJs', 'ReactJS', 'NodeJS'],
    source: 'https://github.com/dabdu/feedback-app',
    visit: 'https://feedback-app-dabdu.vercel.app',
    id: 1,
  },
  {
    title: 'Socail Media Landing Page',
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
    image: 'https://firebasestorage.googleapis.com/v0/b/house-marketplace-b3077.appspot.com/o/portfolio%2Fsocial.png?alt=media&token=5db3cb9a-4744-4964-a65d-ea4e1d4e7879',
    tags: ['NExtJS', 'Tailwind CSS', 'HeroIcons'],
    source: 'https://github.com/dabdu/social-media-landing-page',
    visit: 'https://social-media-landing-page-gold.vercel.app',
    id: 1,
  },

];

export const TimeLineData = [
  { year: 2017, text: 'Started my journey in Tech', },
  { year: 2018, text: 'Worked as a Web Designer @ASAT Infotech Inc', },
  { year: 2019, text: 'Learn New Technologies and Worked FreeLance Developer', },
  { year: 2020, text: 'Went for the First Ever Hackathon and Emerge Winner', },
  { year: 2021, text: 'Become a Software Developer @SpinGoNG', },
];